jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/co_qa:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/co_qa:latest ${{ secrets.DOCKER_USERNAME }}/co_qa:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/co_qa:latest

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Animal-1.0.war
          path: /home/runner/work/Test_CO_CICD/Test_CO_CICD/target/Animals-1.0.war

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test
