name: Java CI with Maven and Testing

on:
  push:
    branches: ["qa"]
  pull_request:
    branches: ["qa"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # path to the Dockerfile and context
          file: ./Dockerfile  # path to the Dockerfile
          push: true
          tags: |
            eliasvr/co_qa:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Animal-1.0.war
          path: /home/runner/work/ci-cd-demo/ci-cd-demo/target/Animals-1.0.war

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test
