name: Deployment Dev

on:
  push:
    branches: [ dev ]

jobs:
  deploy-dev:
    runs-on: [ ubuntu-latest ]
    needs: [ package-dev ]

    steps:
      - name: Run Argo CD sync
        uses: argoproj/argo-cd@v2.2.1/actions/sync
        with:
          repo: https://github.com/Eliasvanroosbroeck/Test_CO_CICD.git
          directory: .
          selector: '*'

      - name: Update application manifests
        # Update image tags or other configuration details for the dev environment

      - name: Apply manifests using Argo CD
        run: argocd cm update
